### ISSUE TITLE
Live - Spamming PMs

### ISSUE THREAD

**Issue by Draaked** [BlocklandGlass/BlocklandGlass#214]
Currently you're able to spam PMs and cause lag on the person that you're PMing if you do it through a script very fast. Should put some small cooldown on PMs if possible.

**Comment by Paperworx** [comment]
this should be able to be handled by the Glass Live server without any client changes, I assume the lag is caused by the abundance of notifications that show up on screen along with the text spam in the DM window -- adding server-side anti-spam should just be enough to give a user time to block the offending user spamming him/her (assuming that blocking stops the lag).
