### ISSUE TITLE
Glass Live - Performance Issues w/ User Events

### ISSUE THREAD

**Issue by Ipquarx** [BlocklandGlass/BlocklandGlass#256]
I've been having some serious stuttering issues with blockland for a while now. I just figured out why exactly they're being caused.
The code associated with users joining, leaving, and updating their status in a room all cause noticeable stuttering even on PCs with decent CPUs.

How I found this out is mainly by looking at trace logs, but just to confirm it I added an echo to whenever one of these events happen by editing /support/jettison.cs to include the following:

![](https://i.imgur.com/GsViwQP.png)

I've uploaded a short video of the results of this:
https://leopard.hosting/dl/dzbwg
https://mega.nz/#!n1JRRCpI!87HdHudxHDeSYuH_6lgRBLRRj9g0RwKMbaQMqnYH7KQ

In addition to this, disconnecting from Glass Live fixes the stuttering issues.
A cursory examination of trace logs seems to indicate that upon every time a user joins, leaves, or updates their status, it checks whether every single person in the room is a bot, mod, or admin. That may be a good place to start.

Finally, I noticed that in the development branch you've switched to using sha256. I'd strongly advise against this. Despite the fact that it is more secure, that extra security is useless in the context of its intended application. This means you have zero benefit for a massive performance loss.

**Comment by Ipquarx** [comment]
Nice, issue 2^8.

**Comment by Jincux** [comment]
I also have some skepticism about using sha256 as I'm sure its' efficiency in torque is pretty terrible, but haven't experimented with it much. Still up for debate before 4.2 release

The efficiency issues is likely with redrawing the userlist - I can't imagine the issue is with jettison since those are typically short message. The sorting method for the user list isn't great, relying on creating several list gui's and using that for sorting. I'll give it a look and see if there's room for optimization and probably put in a more efficient/customized sorting system/algorithm.

Thanks for your detailed bug report!

**Comment by McTwist** [comment]
I suggested the addition only if it wouldn't degrade the performance. More tests needs to be done before it's properly integrated into the latest version.
