### ISSUE TITLE
Updater text overflow

### ISSUE THREAD

**Issue by Jincux** [BlocklandGlass/BlocklandGlass#81]
https://vgy.me/8aMER9.png

**Comment by Jincux** [comment]
Moved to 3.3.0, will work with new scrolling text system

**Comment by Paperworx** [comment]
is there a point to displaying the file name alongside the add-on name on the left?
the file name is already displayed on the right, so removing the file name info on the left would free up space and prevent the overflow unless the add-on's friendly name was very large.

also, the Glass profile theme doesn't appear to be applied on that GUI: is that intentional?
